<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>StudyTime.Application</AssemblyName>
    <RootNamespace>StudyTime.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StudyTime.Domain\StudyTime.Domain.csproj" />
  </ItemGroup>
</Project>