// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyTime.Infrastructure.Persistence;

#nullable disable

namespace StudyTime.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StudyTimeDbContext))]
    partial class StudyTimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyTime.Domain.Entities.StudyArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<int>("StdWeekStudyTime")
                        .HasColumnType("integer")
                        .HasColumnName("std_week_study_time");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tb_study_area", null, t =>
                        {
                            t.HasCheckConstraint("ck_tb_study_area_std_week_study_time_positive", "std_week_study_time > 0");
                        });
                });

            modelBuilder.Entity("StudyTime.Domain.Entities.StudyAreaWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("StudyAreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_area_id");

                    b.Property<Guid>("StudyPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_plan_id");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date")
                        .HasColumnName("week_start_date");

                    b.Property<Guid>("WeeklyAssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("weekly_assessment_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyPlanId");

                    b.HasIndex("WeeklyAssessmentId");

                    b.HasIndex("StudyAreaId", "WeekStartDate")
                        .IsUnique();

                    b.ToTable("tb_study_area_week", null, t =>
                        {
                            t.HasCheckConstraint("ck_tb_study_area_week_start_date_monday", "EXTRACT(ISODOW FROM week_start_date) = 1");
                        });
                });

            modelBuilder.Entity("StudyTime.Domain.Entities.StudyAreaWeekAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MinutesStudied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("minutes_studied");

                    b.Property<Guid>("StudyAreaWeekId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_area_week_id");

                    b.Property<decimal>("WeekIndividualGoal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("week_individual_goal");

                    b.HasKey("Id");

                    b.HasIndex("StudyAreaWeekId")
                        .IsUnique();

                    b.ToTable("tb_study_area_week_assessment", null, t =>
                        {
                            t.HasCheckConstraint("ck_tb_study_area_week_assessment_individual_goal_positive", "week_individual_goal > 0");

                            t.HasCheckConstraint("ck_tb_study_area_week_assessment_minutes_studied_non_negative", "minutes_studied >= 0");
                        });
                });

            modelBuilder.Entity("StudyTime.Domain.Entities.StudyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Coefficient")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("coefficient");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tb_study_plan", null, t =>
                        {
                            t.HasCheckConstraint("ck_tb_study_plan_coefficient_positive", "coefficient > 0");

                            t.HasCheckConstraint("ck_tb_study_plan_status_valid", "status IN ('active', 'inactive')");
                        });
                });

            modelBuilder.Entity("StudyTime.Domain.Entities.StudyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("date")
                        .HasDefaultValueSql("((NOW() AT TIME ZONE 'America/Sao_Paulo')::date)");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<Guid>("StudyAreaWeekId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_area_week_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyAreaWeekId");

                    b.ToTable("tb_study_record", null, t =>
                        {
                            t.HasCheckConstraint("ck_tb_study_record_minutes_positive", "minutes > 0");
                        });
                });

            modelBuilder.Entity("StudyTime.Domain.Entities.WeeklyAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MinutesStudied")
                        .HasColumnType("integer")
                        .HasColumnName("minutes_studied");

                    b.Property<decimal>("WeekGlobalGoal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("week_global_goal");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("Year", "WeekNumber")
                        .IsUnique();

                    b.ToTable("tb_weekly_assessment", null, t =>
                        {
                            t.HasCheckConstraint("ck_tb_weekly_assessment_global_goal_positive", "week_global_goal > 0");

                            t.HasCheckConstraint("ck_tb_weekly_assessment_minutes_studied_non_negative", "minutes_studied >= 0");

                            t.HasCheckConstraint("ck_tb_weekly_assessment_week_number_valid", "week_number BETWEEN 1 AND 53");

                            t.HasCheckConstraint("ck_tb_weekly_assessment_year_positive", "year > 0");
                        });
                });

            modelBuilder.Entity("StudyTime.Domain.Entities.StudyAreaWeek", b =>
                {
                    b.HasOne("StudyTime.Domain.Entities.StudyArea", null)
                        .WithMany()
                        .HasForeignKey("StudyAreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudyTime.Domain.Entities.StudyPlan", null)
                        .WithMany()
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudyTime.Domain.Entities.WeeklyAssessment", null)
                        .WithMany()
                        .HasForeignKey("WeeklyAssessmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyTime.Domain.Entities.StudyAreaWeekAssessment", b =>
                {
                    b.HasOne("StudyTime.Domain.Entities.StudyAreaWeek", null)
                        .WithOne()
                        .HasForeignKey("StudyTime.Domain.Entities.StudyAreaWeekAssessment", "StudyAreaWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyTime.Domain.Entities.StudyRecord", b =>
                {
                    b.HasOne("StudyTime.Domain.Entities.StudyAreaWeek", null)
                        .WithMany()
                        .HasForeignKey("StudyAreaWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
